Practica 2 - Ejercicio 6.5

diff --git a/devops/Jenkinsfile b/devops/Jenkinsfile
--- a/devops/Jenkinsfile
+++ b/devops/Jenkinsfile
@@ -136,6 +136,16 @@ pipeline {
         always {
             // Elimina contenedor
             sh 'docker compose down --volumes'
+            sh 'docker rmi $IMAGE_REPO_LOCAL || true'
+        }
+        success {
+          // Imprime SUCCESS
+          echo 'SUCCESS'
+        }
+        failure {
+          // Imprime FAILURE y muestra logs
+          echo 'FAILURE'
+          sh 'docker compose logs || true'
         }
       }
     }
